#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Values

# Namespaces - Common
MAX_RETRIES = 3
AUTH_TIMEOUT = 30

AUTH_ERROR_TIMEOUT = 1005
AUTH_ERROR_INVALID_TOKEN = 1001
AUTH_ERROR_MISSING_ID = 1002
AUTH_ERROR_INVALID_DETAILS = 1003
AUTH_ERROR_MAX_RETRIES = 1004